services:
  db:
    image: mysql:latest
    volumes:
      - my_ehr:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=motherfucker
      - MYSQL_USER=faithkoko
      - MYSQL_PASSWORD=kpekuspass
      - MYSQL_DATABASE=ehr_baby

volumes:
  my_ehr:
