"""empty message

Revision ID: 183578767f79
Revises: b408550d878a
Create Date: 2025-01-04 22:24:37.039716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '183578767f79'
down_revision = 'b408550d878a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_status', sa.Enum('MARRIED', 'SINGLE', name='relationshipstatus'), nullable=False))
        batch_op.drop_column('married')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('married', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('relationship_status')

    # ### end Alembic commands ###
