"""empty message

Revision ID: 575b4bf38209
Revises: 30c2cc8650c9
Create Date: 2025-01-06 04:11:22.543809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575b4bf38209'
down_revision = '30c2cc8650c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient_record', ['record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('image_ibfk_1', 'patient_record', ['record_id'], ['id'])

    # ### end Alembic commands ###
