"""empty message

Revision ID: b2b982053d62
Revises: 575b4bf38209
Create Date: 2025-01-06 04:13:43.364114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b982053d62'
down_revision = '575b4bf38209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('patient_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.drop_constraint('patient_record_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_record_ibfk_1', 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
