"""empty message

Revision ID: b408550d878a
Revises: e6ef84c13dae
Create Date: 2025-01-04 22:20:06.910323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b408550d878a'
down_revision = 'e6ef84c13dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('married', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('allergies')
        batch_op.drop_column('married')

    # ### end Alembic commands ###
