"""empty message

Revision ID: db3a1fa577fe
Revises: 183578767f79
Create Date: 2025-01-05 06:38:26.409818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3a1fa577fe'
down_revision = '183578767f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.drop_column('medication')

    # ### end Alembic commands ###
