"""empty message

Revision ID: f1c7176e891c
Revises: db3a1fa577fe
Create Date: 2025-01-06 03:06:46.925454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1c7176e891c'
down_revision = 'db3a1fa577fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.Text(), nullable=False))
        batch_op.drop_column('blob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blob', mysql.TEXT(), nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
